# Generated by Django 4.1.3 on 2022-11-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u1_text', models.CharField(max_length=255)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
