# Generated by Django 4.1.3 on 2022-11-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='np_label',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='np_score',
            field=models.IntegerField(null=True),
        ),
    ]
